# Site settings
title: 你家的喵不喝牛奶
email: zn74039585@sina.com
description: > # this means to ignore newlines until "baseurl:"
  每一个程序员都有着一颗Geek的心
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: zndada
github_username:  zndada
GoogleAnalytics: UA-xxxxxx-x

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'

Regeneration: -w


